### ISSUE TITLE
Retrieve customer email and shipping address

### ISSUE THREAD

**Issue by bigfoot90** [schmittjoh/JMSPaymentPaypalBundle#65] opened 2013-09-19 16:20 UTC
How to retrieve customer email and shipping address.
I found the information I'm looking for within the variable $details in the file ExpressCheckoutPlugin.php (Line 161).
But I have no idea how to retrieve this information within my controller.

Any suggestion is appreciated.
Thanks to everyone.

**Comment by regularjack** [comment] 2016-10-16 23:58
Duplicate of #25

**Closed by regularjack** 2016-10-16 23:58 UTC
